### ISSUE TITLE
possible problem with dynamic_pointer_cast

### ISSUE THREAD

**Issue by RiccardoRossi** [lhmouse/intrusive_ptr#4]
Hello,

could it be that the implementation of dynamic pointer_cast is wrong?

i believe it should be:

~~~cpp
 template<typename _U, typename _T>
  intrusive_ptr<_U> my_dynamic_pointer_cast(intrusive_ptr<_T> __r) noexcept {
    const auto __u = dynamic_cast<_U*>(__r.get());
    if(__u){
      __r.release();
    }
    return intrusive_ptr<_U>(__u);
  }
~~~

with $dynamic_cast<_U*>$ as in the code i post instead of $dynamic_cast<_U>$ as in the repository

**Comment by lhmouse** [comment]
Thanks. Those are typos and have been fixed now.
